config setup
    charondebug="ike 2, knl 2, cfg 2"

conn L2TP-PSK
    authby=secret
    auto=add
    keyexchange=ikev1
    type=transport
    left=%defaultroute
    leftprotoport=17/1701
    leftsubnet=192.168.10.250/32[udp/1701]
    right=192.168.10.131
    rightprotoport=17/1701
    rightsubnet=192.168.10.131/32[udp/1701]
    ike=aes256-sha1-modp2048
    esp=aes256-sha1!
    pfs=no
    forceencaps=yes